version: '3.8'

services:
  backend:
    build: ./backend
    container_name: techcorp-backend
    ports:
      - "5000:5000"
    environment:
      - INFERENCE_MODE=ollama
      - INFERENCE_SERVER=http://48.220.35.222:11434
      - MODEL_NAME=phi3-financial
      - BASE_MODEL_NAME=microsoft/Phi-3-mini-4k-instruct
      - MODEL_PATH=../../models/phi3_financial
      - BACKEND_PORT=5000
      - DEBUG=True
      - REQUEST_TIMEOUT=600
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        # Remplacez <VOTRE_IP_PUBLIQUE_AWS> par l'IP publique de votre instance EC2
        - REACT_APP_API_URL=http://52.47.155.186:5000
    container_name: techcorp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped