const express = require("express");
const cors = require("cors");

const app = express();

const PORT = Number(process.env.PORT || 3001);
const OLLAMA_BASE_URL = process.env.OLLAMA_BASE_URL || "http://13.222.248.247:11434";
const DEFAULT_MODEL = process.env.OLLAMA_MODEL || "phi3.5:latest";

app.use(cors());
app.use(express.json({ limit: "2mb" }));

async function checkOllama() {
  const res = await fetch(`${OLLAMA_BASE_URL}/api/tags`, { method: "GET" });
  if (!res.ok) {
    throw new Error(`Ollama status ${res.status}`);
  }
  return res.json();
}

app.get("/api/status", async (_req, res) => {
  try {
    await checkOllama();
    res.json({ connected: true, ollamaBaseUrl: OLLAMA_BASE_URL });
  } catch (err) {
    res.status(503).json({
      connected: false,
      error: err instanceof Error ? err.message : "Unknown error",
      ollamaBaseUrl: OLLAMA_BASE_URL,
    });
  }
});

app.post("/api/chat", async (req, res) => {
  const { model = DEFAULT_MODEL, messages, temperature = 0.7, top_p = 0.9, num_predict = 256 } = req.body || {};

  if (!Array.isArray(messages) || messages.length === 0) {
    return res.status(400).json({ error: "messages must be a non-empty array" });
  }

  try {
    const ollamaRes = await fetch(`${OLLAMA_BASE_URL}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        messages,
        stream: false,
        options: {
          temperature,
          top_p,
          num_predict,
        },
      }),
    });

    const payload = await ollamaRes.json();

    if (!ollamaRes.ok) {
      return res.status(ollamaRes.status).json({
        error: payload?.error || "Ollama chat call failed",
      });
    }

    const answer = payload?.message?.content?.trim();
    return res.json({
      reply: answer || "No response generated by the model.",
      raw: payload,
    });
  } catch (err) {
    return res.status(500).json({
      error: err instanceof Error ? err.message : "Unknown network error",
    });
  }
});

app.listen(PORT, () => {
  console.log(`[backend] TechCorp API running on http://localhost:${PORT}`);
  console.log(`[backend] Target Ollama server: ${OLLAMA_BASE_URL}`);
  console.log(`[backend] Default model: ${DEFAULT_MODEL}`);
});
